version: '3'

services: 

    postgres:
        container_name: postgres_db
        image: postgres:9.6.6
        env_file: 
            - ../.env
        ports: 
            - 5432:5432 
        volumes: 
            - ../postgre_db:/var/lib/postgresql/data